GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/ñakañaka

###
GET http://localhost:3001/api/notes/

###
PUT http://localhost:3001/api/notes/673ea8a5abf30be0141dc890
Content-Type: application/json

{
    "content": "Testing",
    "important": true
}


###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Testing",
    "important": true
}

###
GET http://localhost:3001/api/notes/115

###
GET http://localhost:3001/api/walala

###
DELETE  http://localhost:3001/api/notes/673e9301082e4aa7201b36d8

