GET http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/notes/ñakañaka

###
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/users

###
PUT http://localhost:3001/api/notes/673ea8a5abf30be0141dc890
Content-Type: application/json

{
    "content": "Testing",
    "important": true
}


###
POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1c2hhcmRvcG9saXMiLCJpZCI6IjY3NDEzNWZiMmRhMmVmMWExNTg2OGQyZiIsImlhdCI6MTczMjMyOTgwOH0.oeTnbYbldwYIbDz03oYxd0kUJcYTCRK0x-_7sT-rso8

{
    "content": "Ha llegao el auth",
    "important": true
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer 

{
    "content": "RRRRR",
    "important": true
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Gushardopolis",
    "name": "gushi",
    "password": "awa"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Gushardopolis",
    "password": "awa"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Gushardopolis",
    "password": "cualquiercosa"
}

###
GET http://localhost:3001/api/notes/115

###
GET http://localhost:3001/api/walala

###
DELETE  http://localhost:3001/api/notes/673e9301082e4aa7201b36d8

